### ISSUE TITLE
FORCE_HTTP2 seems to do nothing

### ISSUE THREAD

**Issue by danilobuerger** [OpenSlides/openslides3-autoupdate-service#103]
Setting FORCE_HTTP2 in the Dockerfile seems to do nothing. I would expect setting this to no or false to turn off the http2 requirement set by the middleware.

**Comment by ostcar** [comment]
The option was removed: https://github.com/OpenSlides/openslides3-autoupdate-service/pull/97

**Comment by danilobuerger** [comment]
@ostcar Thanks for the clarification. Then it probably should be removed from the Dockerfile too? Is there a reason why http2 is required even though it works without it?

**Comment by ostcar** [comment]
You are right. I remove it from the Dockerfile.

http1.1 works in theory. But browsers open only a small amount of http1.1 connects to a domain ([see this list](https://docs.pushtechnology.com/cloud/latest/manual/html/designguide/solution/support/connection_limitations.html)).

If you would use http1.1 connections to the autoupdate service, each connection would use one of this connections forever. If you open 6 tabs, then all connections are used. Then it is not possible, to send other request to this domain.

With http2, there is only one tcp connection per Domain. http2 uses multiplexing to send all request via this one tcp connection. So the connection limit is not relevant anymore.

This means, practically, you can not use the autoupdate-service with http1.1.

But http2 has another problem. The browsers require https to use http2. This means, you can only use the autoupdate-service with https. When I started to develop the service, this was a problem, because it was hard for me to generate valid certificates. Therefore I created the environment variable FORCE_HTTP2 (default was false) to develop the service without https. Later, I found some workarounds to use https even in development. For example, see `make dev-cert`.

With #97, I removed the option and always force http2 , so no one uses http1.1 in production by accident.

**Comment by danilobuerger** [comment]
Thanks for the background info, I really appreciate it!

**Comment by danilobuerger** [comment]
@ostcar A quick follow up on this: when using a tls / http2 terminating load balancer, there is really no need to force http2 as it will work just fine with http1 (see for example https://www.nginx.com/blog/7-tips-for-faster-http2-performance/#tip2terminate ).

**Comment by ostcar** [comment]
You right. I don't know why I did not think about it.I will change it
