### ISSUE TITLE
Required user to see on votes

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides3-autoupdate-service#122]

**Comment by FinnStutzenstein** [comment]
What should I do here?

**Comment by ostcar** [comment]
Sorry, I created the issue during a telephone with Emanuel and forgot to add the description.

When a user does not have the permission to see users, but can see a non-anonymous vote with votes, then all the names of the vote_users are hidden.

To solve this, a required user to see function has to be added at the autoupdate service.

Could you do this?

**Comment by FinnStutzenstein** [comment]
Did you test motion polls during the phone call?

It seems, that is is correctly implemented for assignment polls: https://github.com/OpenSlides/openslides3-autoupdate-service/blob/master/internal/apps/assignment/required_users.go#L40

Looks good:
- assignments/assignment-poll:voted_id
- assignments/assignment-option:user_id
- assignments/assignment:assignment-related-user -> user_id

For motions the `motions/motion-poll:voted_ids` code is there, but named `option`: https://github.com/OpenSlides/openslides3-autoupdate-service/blob/master/internal/apps/motion/required_users.go#L32

Is it registered for `motion-option` instead of `motion-poll`?

**Comment by ostcar** [comment]
We only tested motion polls.

I don't know the correct collection for connecting the object. I would think it has to be motion-vote.

**Comment by FinnStutzenstein** [comment]
It is sufficient to use `voted_ids` in the poll since this is the set of all user ids voted.

**Comment by jsangmeister** [comment]
The required users routine for motion poll options does not make sense: Motion options do not have a field `voted_id`, which leads to this function always returning `map[0:true]` - which would tell the caller that the anonymous is required. Luckily this seems to not have caused any problems yet, but nevertheless we should add a check/test for this somewhere.

I will leave this up to @ostcar if that's okay. I will fix the error though in a new PR since we need this feature for https://github.com/OpenSlides/OpenSlides/pull/5978.

**Comment by FinnStutzenstein** [comment]
Additionally, [this error](https://github.com/OpenSlides/openslides3-autoupdate-service/blob/e611d1caa220259a4ad75ec5774437120b9dd735/internal/apps/motion/required_users.go#L37) never triggers. Please check for other places in the code!

**Comment by ostcar** [comment]
It seems that the original issue is done. I don't understand what else you want me to do. I try to answer your question. If there are any other issues, please open a new one.

`json.Unmarshal` only fails, if it gets invalid json or the types on the struct do not match. It does not fail, if fields are missing. See: https://play.golang.org/p/AxyIyaaVvcb
