### ISSUE TITLE
respect _no_delete_on_restriction flag

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides3-autoupdate-service#129]
See https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/utils/autoupdate_bundle.py#L39

This flag is currently send to every client. It has to be removed as well as handled.

**Comment by ostcar** [comment]
I remember, that we talked about it, but I forgot what was the reason for this flag.

Can you explain to me again why we need it? Is it possible to remove it from the python-code?

**Comment by FinnStutzenstein** [comment]
> Is it possible to remove it from the python-code?
The read-part, yes. As well as the access permission classes and the read-part of the rest api. But not the write-part.

> Can you explain to me again why we need it?

To hide autoupdates from users who should not get autoupdates for these models. Especially used for personal notes. An autoupdate should only be issues to users belonging to the personal note. Currently when user A saves a personal note, user B gets an autoupdate. This flag prevents the autoupdate.

**Comment by ostcar** [comment]
I don't see, why this is necessary. The additional autoupdates do no harm. Could you just remove the flag from python?

**Comment by FinnStutzenstein** [comment]
> The additional autoupdates do no harm. 

They do, this is the reason we introduced this feature!

**Comment by ostcar** [comment]
Could you explain to me the problem? If you like, we could do it via telephone.

**Comment by ostcar** [comment]
I talked with @emanuelschuetze. It is ok for him to remove this feature. To many autoupdates are not a problem for the server anymore. If the client has problems, it should skip empty autoupdate-messages.

In os4 the problem is solved that the server knows what version of the data the client has. It only sends data, if the data has changed for the client. If we need, I could add this functionality to os3 as well.
