### ISSUE TITLE
InternalError on notify

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides3-autoupdate-service#64]
I occasionally see `{type: "InternalError", msg: "Ups, something went wrong!"}` without any further information on notify. Can you look through the complete code and insert meaningful errors everywhere?

**Comment by ostcar** [comment]
If there is an internal error, there should be a log message with more information. If this log message is missing, then it is a bug.

Please give me more information, what you did, so I can reproduce it.

**Comment by ostcar** [comment]
Here is the code where the error message `InternalError` is written to the client. It is hard to believe that such an error is send to the client without a log message: https://github.com/OpenSlides/openslides3-autoupdate-service/blob/master/internal/http/http.go#L94..L95

**Comment by FinnStutzenstein** [comment]
Ah It happended again (Maybe you can experience it on the provided instanve via email): `Internal Error: decoding message: unexpected end of JSON input`

**Comment by ostcar** [comment]
It sounds, as if invalid json is processed. All notify-messages are saved in redis. Could you check there if there is a message with invalid json? The redis key is `notify`.

This is strange, because the json should be validated at this line: https://github.com/OpenSlides/openslides3-autoupdate-service/blob/181c368cc07ff5017862dfea9949730ddf082776/internal/notify/http.go#L40

I was not able to send invalid json to the server.

But when I add invalid json into redis directly, I get your error message:
`xadd notify * content '{"channel_id":"foo:1:0", "name":"title", "to_all":true, "message":'`

I think somehow the message gets corrupted. But where?

**Comment by FinnStutzenstein** [comment]
Hi, it still appears. I added some debugging before the `Unmarshal`: https://github.com/FinnStutzenstein/openslides3-autoupdate-service/commit/d8d0e76c1e26a08e02dbeab2d8f67c3cbff52e8f

Received notify 1 messages:
rMail[0]=''
Internal Error: decoding message 0: unexpected end of JSON input

The issue is in the topic library, if it suppose to return valid strings.

**Comment by FinnStutzenstein** [comment]
Note that in this instance I never did a notify before, so there is not `topic` key in redis. But this is not limited to this case - even if I do notifies I sometimes get the error.

**Comment by ostcar** [comment]
Could you find out how to reproduce it? It would help me to fix this.

**Comment by FinnStutzenstein** [comment]
No, just start it. It sometimes appears after a few minutes, sometimes after some hours...

**Comment by ostcar** [comment]
Is it really enough to start the Docker Containers or do I also have to play around in the client?

**Comment by FinnStutzenstein** [comment]
> or do I also have to play around in the client?

I start it and log in to even build a connection to the notify endpoint, so I get the error in the client. Nothing more to be done, especially I do not send any notify.
